### ISSUE TITLE
Lambda2M timed out after first measurement because `cam1.NumTriggers_RBV` not found

### ISSUE THREAD

**Issue by qzhang234** [aps-8id-trr/ipython-8idiuser#292]
@prjemian  Lambda2M timed out after the first measurement because it timed out on `cam1.NumTriggers_RBV`. 

My first reaction was to comment out that PV in the detector class definition, but then I realized that the error did not pass through `ad_Lambda2M.py` at all. Any suggestions?

[Output_Terminal.txt](https://github.com/aps-8id-dys/ipython-8idiuser/files/8792930/Output_Terminal.txt)

**Comment by prjemian** [comment]
Does this PV (`8idLambda2m:cam1:NumTriggers_RBV`) exist?

**Comment by qzhang234** [comment]
@prjemian Looks like the PV does not exist. Any suggestions?

![image](https://user-images.githubusercontent.com/48140482/175396697-4e5907ae-2e65-424d-800e-57193b33ebc5.png)

**Comment by prjemian** [comment]
No such NumTriggers feature in that camera.
So in your Python cam class, set `num_triggers = None`

**Comment by prjemian** [comment]
In conversation, we changed the base class for the cam class, from ophyd's Eiger cam to ophyd's Lambda750k cam.

**Comment by qzhang234** [comment]
Will push today's code to branch 150-Lambda2M

**Comment by prjemian** [comment]
In `AD_Acquire` there is a `path` kwarg that is used to set the path the detector uses to write image files and also the path that bluesky will write the DM workflow file.  Can't do that since the Lambda2M does not have the same filesystems as the bluesky workstation.  Execution fails here: https://github.com/aps-8id-dys/ipython-8idiuser/blob/73d28f5ae6dcf3066e8d9bc79ea7d5ac91b7c041/profile_bluesky/startup/instrument/plans/xpcs_acquire.py#L295-L297 with a permissions error.  Suggest refactoring with pathlib and consider `det.hdf1.read_path_template` and `det.hdf1.write_path_template`.  Also, clarify the meaning of the `path` kwarg (IOC or Bluesky sense).

**Comment by qzhang234** [comment]
I think we want `path` in `AD_Acquire` to be consistent with Bluesky sense (`/home/8ididata/2022-2/****`)

**Comment by prjemian** [comment]
We resolved the Lambda2M NumTriggers question in today's meeting, by starting from the `ophyd.Lambda750kCam` class.
